# This is a action to rollback
# COPYRIGHT 2021 Api Prices Project

name: Api Prices Project Rollback Server

on:
  workflow_dispatch:

jobs:
    rollback:
      runs-on: [ubuntu, golang, self-hosted]
      steps:
        - name: Checkout repo code
          uses: actions/checkout@v2

        - name: Rollback docker-compose to server
          uses: matiasnu/github-action-ssh-docker-compose@v2.0.3

          with:
            ssh_host: ${{ secrets.SERVER_SSH_HOST }}
            ssh_user: ${{ secrets.SERVER_SSH_USERNAME }}
            ssh_private_key: ${{ secrets.SERVER_SSH_PRIVATE_KEY}}
            ssh_port: ${{ secrets.SERVER_SSH_PORT}}
            docker_compose_prefix: api_prices_project
            docker_compose_filename: environment/docker-compose.yml
            docker_compose_down: 'true'